apiVersion: v1
kind: Service
metadata:
  name: {{ include "my-app.fullname" . }}-svc
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ include "my-app.name" . }}
spec:
  selector:
    app: {{ include "my-app.name" . }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.containerPort }}
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
  type: {{ .Values.service.type }}
